version: '3.3'

services:
  db:
    image: mysql:8.0
    container_name: 1_db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - '3306:3306'
    expose:
      - 3306
    env_file:
      - .env

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: 1_phpmyadmin
    ports:
      - '81:80'
    expose:
      - 8080
    env_file:
      - phpmyadmin.env

volumes:
  db_data: